[package]
name = "voicevox-dyn"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8.0"
tracing = "0.1.37"
color-eyre = "0.6.2"
ouroboros = "0.18.0"
ureq = "2.7.1"

[dev-dependencies]
tracing-subscriber = "0.3"
